
CREATE TABLE IF NOT EXISTS
   users (
      user_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      personal_amount real DEFAULT 0,
      market_amount real DEFAULT 0,
      created_timestamp timestamp with time zone DEFAULT NOW() NOT NULL
   );

CREATE TABLE IF NOT EXISTS
   personal_events (
      event_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      user_id integer REFERENCES users ON DELETE CASCADE NOT NULL,
      event_description text NOT NULL,
      finished_timestamp timestamp with time zone, -- NULL means not finished
      net_result real,
      notes TEXT,
      created_timestamp timestamp with time zone DEFAULT NOW() NOT NULL
   );

CREATE TABLE IF NOT EXISTS
   personal_event_options (
      option_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      event_id integer REFERENCES personal_events ON DELETE CASCADE NOT NULL,
      option_description text NOT NULL,
      bet_amount real NOT NULL
   );

ALTER TABLE personal_events ADD COLUMN IF NOT EXISTS
      winning_option integer REFERENCES personal_event_options ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS
   market_events (
      event_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      event_description text NOT NULL,
      finished_timestamp timestamp with time zone, -- NULL means not finished
      created_timestamp timestamp with time zone DEFAULT NOW() NOT NULL
   );

CREATE TABLE IF NOT EXISTS
   market_event_options (
      option_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      event_id integer REFERENCES market_events ON DELETE CASCADE NOT NULL,
      option_description text NOT NULL,
      odds real NOT NULL
   );

ALTER TABLE market_events ADD COLUMN IF NOT EXISTS
      winning_option integer REFERENCES market_event_options ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS
   market_event_picks (
      pick_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      event_id integer REFERENCES market_events ON DELETE CASCADE NOT NULL,
      option_id integer REFERENCES market_event_options ON DELETE CASCADE NOT NULL,
      user_id integer REFERENCES users ON DELETE CASCADE NOT NULL,
      net_result real,
      notes TEXT,
      created_timestamp timestamp with time zone DEFAULT NOW() NOT NULL
   );
