
CREATE TABLE IF NOT EXISTS
   users (
      user_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (
         START WITH 1398),
      personal_amount real DEFAULT 0,
      market_amount real DEFAULT 0,
      created_timestamp timestamp with time zone DEFAULT NOW()
   );

CREATE TABLE IF NOT EXISTS
   personal_events (
      event_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (
         START WITH 10527),
      user_id integer REFERENCES users ON DELETE CASCADE NOT NULL,
      event_description text NOT NULL,
      finished boolean NOT NULL,
      winning_option integer, -- REFERENCES personal_event_options,
      net_result real DEFAULT 0,
      notes TEXT DEFAULT '',
      created_timestamp timestamp with time zone DEFAULT NOW()
   );

CREATE TABLE IF NOT EXISTS
   personal_event_options (
      option_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (
         START WITH 21339),
      event_id integer REFERENCES personal_events ON DELETE CASCADE NOT NULL,
      option_description text NOT NULL,
      bet_amount real NOT NULL
   );

CREATE TABLE IF NOT EXISTS
   market_events (
      event_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (
         START WITH 2527),
      event_description text NOT NULL,
      finished boolean NOT NULL,
      winning_option integer, -- REFERENCES market_event_options,
      created_timestamp timestamp with time zone DEFAULT NOW()
   );

CREATE TABLE IF NOT EXISTS
   market_event_options (
      option_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (
         START WITH 2339),
      event_id integer REFERENCES market_events ON DELETE CASCADE NOT NULL,
      option_description text NOT NULL,
      odds real NOT NULL
   );

CREATE TABLE IF NOT EXISTS
   market_event_picks (
      pick_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (
         START WITH 8790),
      event_id integer REFERENCES market_events ON DELETE CASCADE NOT NULL,
      option_id integer REFERENCES market_event_options ON DELETE CASCADE NOT NULL,
      user_id integer REFERENCES users ON DELETE CASCADE NOT NULL,
      net_result real DEFAULT 0,
      notes TEXT DEFAULT '',
      created_timestamp timestamp with time zone DEFAULT NOW()
   );
